In [3]:
import pandas as pd
import numpy as np

In [5]:
combined_df = pd.read_csv('Combined_Dataframe.csv')

In [6]:
combined_df[combined_df.title=='University_of_Notre_Dame']

title  bm25_score  bm25_rank  tfidf_score  \
422       University_of_Notre_Dame   22.617357          1     0.053244   
864       University_of_Notre_Dame   18.809760          1     0.358710   
1306      University_of_Notre_Dame   16.853517          1     0.380284   
1748      University_of_Notre_Dame   23.213694          1     0.310079   
2190      University_of_Notre_Dame   13.112193          1     0.407653   
2632      University_of_Notre_Dame   19.286762          1     0.287946   
3074      University_of_Notre_Dame    9.908088          2     0.304790   
3516      University_of_Notre_Dame   14.322584          1     0.166318   
3958      University_of_Notre_Dame    8.758392          1     0.310321   
4400      University_of_Notre_Dame   15.213747          1     0.325856   
4842      University_of_Notre_Dame   10.386947          2     0.313690   
5284      University_of_Notre_Dame    6.788079          1     0.355722   
5726      University_of_Notre_Dame   10.690416          1     0.045494   
6168      University_of_Notre_Dame   12.977349          1     0.044660   
6610      University_of_Notre_Dame    9.868910          1     0.019598   
7052      University_of_Notre_Dame   17.969331          1     0.350022   
7494      University_of_Notre_Dame   21.507839          1     0.299295   
7936      University_of_Notre_Dame   14.321255          1     0.067136   
8378      University_of_Notre_Dame   18.575876          3     0.323735   
8820      University_of_Notre_Dame   18.466575          3     0.320193   
9262      University_of_Notre_Dame   16.156587          1     0.366301   
9704      University_of_Notre_Dame    9.637220          3     0.295896   
10146     University_of_Notre_Dame   19.749869          1     0.282019   
10588     University_of_Notre_Dame   11.902125          5     0.309585   
11030     University_of_Notre_Dame   13.024873          2     0.293494   
11472     University_of_Notre_Dame   21.324960          1     0.350649   
11914     University_of_Notre_Dame    1.872534         21     0.012595   
12356     University_of_Notre_Dame   16.735873          1     0.309794   
12798     University_of_Notre_Dame   19.280689          2     0.334047   
13240     University_of_Notre_Dame   11.107305          1     0.031966   
...                            ...         ...        ...          ...   
38632548  University_of_Notre_Dame    2.968404         44     0.005257   
38632990  University_of_Notre_Dame    1.177262        194     0.012184   
38633432  University_of_Notre_Dame    1.903201         76     0.003538   
38633874  University_of_Notre_Dame    1.026927         65     0.006050   
38634316  University_of_Notre_Dame    4.890455         31     0.008628   
38634758  University_of_Notre_Dame    5.218825         16     0.018115   
38635200  University_of_Notre_Dame    7.426182         11     0.126218   
38635642  University_of_Notre_Dame    2.382322         17     0.004888   
38636084  University_of_Notre_Dame    8.255710          3     0.027647   
38636526  University_of_Notre_Dame    4.461950         16     0.011266   
38636968  University_of_Notre_Dame    0.000000        442     0.013890   
38637410  University_of_Notre_Dame    4.626538          9     0.011820   
38637852  University_of_Notre_Dame    0.719346        360     0.013629   
38638294  University_of_Notre_Dame    5.255907          5     0.018244   
38638736  University_of_Notre_Dame    3.808780         16     0.008418   
38639178  University_of_Notre_Dame    0.274366        313     0.000700   
38639620  University_of_Notre_Dame    0.400481        329     0.006543   
38640062  University_of_Notre_Dame    0.916675        371     0.000963   
38640504  University_of_Notre_Dame    0.958074        199     0.003312   
38640946  University_of_Notre_Dame    1.552508        105     0.001279   
38641388  University_of_Notre_Dame    0.646518        123     0.002494   
38641830  University_of_Notre_Dame    2.978922        141     0.006391   
38642272  University_of_Notre_Dam

In [7]:
normalized_combined_df = combined_df

In [8]:
normalized_combined_df.isna().sum()

title              0
bm25_score         0
bm25_rank          0
tfidf_score        0
tfidf_rank         0
doc2vec_score      0
doc2vec_rank       0
question           0
Actual_Document    0
dtype: int64

In [9]:
normalized_combined_df['bm25_score'] = (normalized_combined_df.bm25_score-min(normalized_combined_df.bm25_score))/(max(normalized_combined_df.bm25_score)-min(normalized_combined_df.bm25_score))
normalized_combined_df['tfidf_score']=(normalized_combined_df.tfidf_score-min(normalized_combined_df.tfidf_score))/(max(normalized_combined_df.tfidf_score)-min(normalized_combined_df.tfidf_score))
normalized_combined_df['doc2vec_score']=(normalized_combined_df.doc2vec_score-min(normalized_combined_df.doc2vec_score))/(max(normalized_combined_df.doc2vec_score)-min(normalized_combined_df.doc2vec_score))

In [10]:
normalized_combined_df.head()

title  bm25_score  bm25_rank  tfidf_score  \
0           2008_Sichuan_earthquake    0.002787        311     0.000690   
1  2008_Summer_Olympics_torch_relay    0.048700         45     0.008462   
2                        51st_state    0.075982         13     0.018628   
3                             ASCII    0.006013        211     0.002844   
4                        A_cappella    0.013270        181     0.001741   

   tfidf_rank  doc2vec_score  doc2vec_rank  \
0         347       0.683617            11   
1          79       0.667423            22   
2          41       0.411718           382   
3         216       0.564947           150   
4         277       0.485875           287   

                                            question  Actual_Document  
0  To whom did the Virgin Mary allegedly appear i...                0  
1  To whom did the Virgin Mary allegedly appear i...                0  
2  To whom did the Virgin Mary allegedly appear i...                0  
3  To whom did the Virgin Mary allegedly appear i...                0  
4  To whom did the Virgin Mary allegedly appear i...                0

In [11]:
X = normalized_combined_df[['bm25_score','tfidf_score','doc2vec_score']]

In [12]:
X.head()

bm25_score  tfidf_score  doc2vec_score
0    0.002787     0.000690       0.683617
1    0.048700     0.008462       0.667423
2    0.075982     0.018628       0.411718
3    0.006013     0.002844       0.564947
4    0.013270     0.001741       0.485875

In [13]:
y = normalized_combined_df[['Actual_Document']]

In [14]:
y.head()

Actual_Document
0                0
1                0
2                0
3                0
4                0

In [ ]:
y.shape

In [ ]:
X.shape

In [20]:
y_categorical = keras.utils.to_categorical(y)

In [14]:
import keras

Using TensorFlow backend.


In [15]:
from keras.models import Sequential
from keras.layers import LSTM,Dense
from keras.optimizers import RMSprop,Adam

In [21]:
model1 = Sequential()
model1.add(Dense(64,input_dim=3))
model1.add(Dense(128,activation='relu'))
model1.add(Dense(2,activation='softmax'))

In [22]:
model1.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [23]:
z = [keras.callbacks.EarlyStopping(monitor="val_acc", min_delta=0.01, patience=3, verbose=1, mode='max')]

In [25]:
model1.fit(X,y_categorical,batch_size=10,epochs=1,callbacks=z)

Epoch 1/1
38645386/38645386 [==============================] - 3262s 84us/step - loss: 0.0074 - acc: 0.9983


c:\program files\python36\lib\site-packages\keras\callbacks.py:535: RuntimeWarning: Early stopping conditioned on metric `val_acc` which is not available. Available metrics are: loss,acc
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


In [27]:
y_pred = model1.predict(X)

In [30]:
y_pred

array([[9.9999797e-01, 2.0674820e-06],
       [9.9992657e-01, 7.3413932e-05],
       [9.9963641e-01, 3.6358903e-04],
       ...,
       [9.9999833e-01, 1.6974371e-06],
       [9.9999797e-01, 1.9796539e-06],
       [9.9999869e-01, 1.3334197e-06]], dtype=float32)

In [32]:
model1.evaluate(X,y_categorical)

38645386/38645386 [==============================] - 418s 11us/step


[0.007919588009540731, 0.9984774120253321]

In [58]:
model1.save_weights('weight.txt')

In [59]:
for layer in model1.layers:
    weights = layer.get_weights() # list of numpy arrays

In [60]:
weights

[array([[ 1.05214126e-01,  2.63342112e-02],
        [-6.42250776e-02, -4.12807427e-02],
        [-9.64133069e-03,  3.00992560e-02],
        [ 1.21901833e-01,  2.34762523e-02],
        [ 6.51827812e-01, -5.45319736e-01],
        [ 7.73876533e-02,  1.00423492e-01],
        [ 2.45274812e-01, -2.20042080e-01],
        [ 3.00370660e-02, -1.65700555e-01],
        [-2.33952906e-02, -4.93188016e-03],
        [ 1.88144278e-02, -4.58042473e-02],
        [ 3.31196487e-01, -4.27753091e-01],
        [-1.32346854e-01, -5.69821671e-02],
        [ 7.98862427e-02, -1.63563892e-01],
        [-4.95735817e-02, -2.81939775e-01],
        [ 4.96616475e-02,  4.52414937e-02],
        [-1.66057199e-01, -1.45493835e-01],
        [ 1.83826432e-01, -1.07162975e-01],
        [-2.13652715e-01, -2.80539375e-02],
        [ 5.17142192e-02,  9.50651392e-02],
        [ 8.25107843e-02,  1.39628097e-01],
        [ 6.18398413e-02,  1.80593550e-01],
        [ 1.16783470e-01, -3.43369097e-02],
        [-3.00872587e-02,  3.043

In [68]:
from sklearn.linear_model import LogisticRegression,LinearRegression

In [36]:
model2 = LogisticRegression()

In [38]:
from sklearn.cross_validation import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [40]:
model2.fit(X_train,y_train)

c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
y_pred2 = model2.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred2)
print(confusion_matrix)

[[11563840     3584]
 [   14083    12109]]


In [45]:
(11563840+12109)/(3584+14083+11563840+12109)

0.9984761441124149

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00  11567424
          1       0.77      0.46      0.58     26192

avg / total       1.00      1.00      1.00  11593616



In [50]:
model2.intercept_

array([38.81270882])

In [53]:
model2.coef_

array([[-30.97164397, -15.76856947,  -0.47114933]])

In [61]:
#Equation = 38.81270882-30.97164397* bm25_score - 15.76856947*tfidf_score - 0.47114933*doc2vec_score

In [62]:
normalized_combined_df.head()

title  bm25_score  bm25_rank  tfidf_score  \
0           2008_Sichuan_earthquake    0.997213        311     0.999310   
1  2008_Summer_Olympics_torch_relay    0.951300         45     0.991538   
2                        51st_state    0.924018         13     0.981372   
3                             ASCII    0.993987        211     0.997156   
4                        A_cappella    0.986730        181     0.998259   

   tfidf_rank  doc2vec_score  doc2vec_rank  \
0         347       0.316383            11   
1          79       0.332577            22   
2          41       0.588282           382   
3         216       0.435053           150   
4         277       0.514125           287   

                                            question  Actual_Document  
0  To whom did the Virgin Mary allegedly appear i...                0  
1  To whom did the Virgin Mary allegedly appear i...                0  
2  To whom did the Virgin Mary allegedly appear i...                0  
3  To whom did the Virgin Mary allegedly appear i...                0  
4  To whom did the Virgin Mary allegedly appear i...                0

In [77]:
model3 = LinearRegression(fit_intercept=False)

In [78]:
model3.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [79]:
y_pred3 = model3.predict(X_test)

In [80]:
model3.coef_

array([[ 0.45938666, -0.46303214,  0.02230693]])

In [81]:
model3.intercept_

0.0

In [83]:
0.45938666* 0.997213 - 0.46303214*0.999310 - 0.02230693*0.316383

-0.011663831879009968

In [89]:
model3.score(X_test,y_test)

0.03902012233575258